### ISSUE TITLE
Malformed JSON string line 81

### ISSUE THREAD

**Issue by onash** [brutog/bettertron#9]
I am getting this error when trying to run this on my whatbox seedbox...I am not sure what it could be.

**Comment by brutog** [comment]
That is really early on during the whole process. That's when the script decodes the JSON returned from the first login using your username and password to grab your auth/pass key. It would seem that the submission worked but the return was empty or bad. My guess would be empty.

My guess is what.cd or the what.cd api was down when you tried. Did you try again and see if it works now?

**Comment by onash** [comment]
It is fixed now.

All is not well though. When running the script I get an error saying it
can not find the transcode directory. Any ideas on this?

Owen

**Comment by brutog** [comment]
I answered a similar question in the thread on what. I'll paste what I said here:

 It means no directory matching the torrent it was going to transcode was found in the "flacdir" directory you defined in the better.ini. Generally, I never run into it, because the names are retrieved from the whatapi, which match the names of the directories. The albums to transcode are grabbed from the "seeding" section, so you should be seeding them and still have them.

Some torrent clients support changing the name of the directory....if you do this, it will make it impossible for bettertron to figure out what to transcode.
